# Generated by Django 4.0.5 on 2022-06-28 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_contactdetails_tags_contact_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactDetails",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="contact_details_by_foreign_key",
        ),
        migrations.DeleteModel(
            name="ContactDetailsOptions",
        ),
    ]
