# Generated by Django 4.0.5 on 2022-06-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contacts', '0012_remove_contact_tags_by_foreign_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags_by_foreign_key',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='contact_tags_related_by_foreign_key',
                                    to='contacts.tags'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.CharField(blank=True, choices=[('family', '#family'),
                                                        (
                                                        'friends', '#friends'),
                                                        ('trip',
                                                         '#trip_to_planet_c-137')],
                                   default='trip',
                                   help_text="Contact's personalized tags",
                                   max_length=50, verbose_name='Tags'),
        ),
    ]
