# Generated by Django 4.0.6 on 2022-08-03 18:56

import apps.contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0014_alter_contact_birthday_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=apps.contacts.models.get_icon_path,
                verbose_name="Profile picture",
            ),
        ),
    ]
