from apps.contacts.views.contact_create_view import ContactCreateView
from apps.contacts.views.contact_delete_view import DeleteContactsView
from apps.contacts.views.contact_update_view import ContactUpdateView
from apps.contacts.views.show_all_contacts import ShowAllContactsView
