# Generated by Django 4.0.5 on 2022-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name="User's name")),
                ('log_path', models.CharField(max_length=1000, verbose_name='Path to the log data')),
                ('user_is_auth', models.CharField(max_length=200, verbose_name='Shows whether the user is authenticated or not')),
                ('latest_entry', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
